//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Petshop
{
    using System;
    using System.Collections.Generic;
    
    public partial class ProductCharacteristics
    {
        public int ProductId { get; set; }
        public int CharacteristicId { get; set; }
        public string СharacteristicValue { get; set; }
    
        public virtual Characteristics Characteristics { get; set; }
        public virtual Products Products { get; set; }
    }
}
