//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Petshop
{
    using System;
    using System.Collections.Generic;
    
    public partial class Products_in_cart
    {
        public int id_product { get; set; }
        public int id_cart { get; set; }
        public Nullable<int> count_of_products { get; set; }
    
        public virtual Carts Carts { get; set; }
        public virtual Products Products { get; set; }
    }
}
